type: object
description: A configuration for a field.
required:
  - name
properties:
  name:
    description: >
      The name of the field, as defined in our APIs. You can also include custom
      fields.
    type: string
    enum:
      - companyName
      - phoneNumber
      - address
      - addressLine2
      - city
      - region
      - country
      - postalCode
      - couponCode
      - quantity
  setting:
    description: >
      If you want the field hidden, optional, or required.  Some fields may be
      required by a specific theme, and these settings will not override that.

      Defaults are that most fields are shown.  You may wish to hide
      `couponCode`, if you don't use coupons.  You may wish to require specific
      fields

      that are optional (eg `phoneNumber`).
    type: string
    enum:
      - hidden
      - optional
      - required
  label:
    description: >-
      If you want to override the default label, you can set a value here (eg,
      instead of "First Name", you can set "Given Name").
    type: string
  default:
    description: >-
      Set a default value for the field.  It will default to being empty, or 1
      for `quantity`.
    type: string
