parameters:
  - $ref: '#/components/parameters/organizationId'
  - $ref: '#/components/parameters/resourceId'
post:
  tags:
    - Email Delivery Settings
  summary: Resend verification email for an email delivery setting.
  operationId: ResendEmailDeliverySettingVerification
  description: |
    Resend verification email for an email delivery setting.
  responses:
    200:
      description: Verification email was sent successfully.
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/Unauthorized'
    403:
      $ref: '#/components/responses/Forbidden'
    404:
      $ref: '#/components/responses/NotFound'
    409:
      $ref: '#/components/responses/Conflict'
