parameters:
  - $ref: '#/components/parameters/organizationId'
get:
  tags:
    - Email Delivery Settings
  summary: Retrieve a list of email delivery settings
  operationId: GetEmailDeliverySettingCollection
  responses:
    200:
      description: A list of email delivery settings was retrieved successfully
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
        Pagination-Total:
          $ref: "#/components/headers/Pagination-Total"
        Pagination-Limit:
          $ref: "#/components/headers/Pagination-Limit"
        Pagination-Offset:
          $ref: "#/components/headers/Pagination-Offset"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/AccessForbidden'
post:
  tags:
    - Email Delivery Settings
  summary: Create an email delivery setting
  operationId: PostEmailDeliverySetting
  description: |
    Create an email delivery setting.  The email delivery setting is used in conjunction with email messages or templates to send emails.
  responses:
    201:
      description: Email delivery setting was created
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/AccessForbidden'
    422:
      $ref: '#/components/responses/InvalidDataError'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/EmailDeliverySetting'
    description: Email delivery setting resource
    required: true
