parameters:
  - $ref: '#/components/parameters/resourceId'
get:
  tags:
    - Email Delivery Settings
  summary: Retrieve an email delivery setting
  operationId: GetEmailDeliverySetting
  description: |
    Retrieve an email delivery setting
  responses:
    200:
      description: Email delivery setting with specified identifier was retrieved successfully
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/Unauthorized'
    403:
      $ref: '#/components/responses/Forbidden'
    404:
      $ref: '#/components/responses/NotFound'
delete:
  tags:
    - Email Delivery Settings
  summary: Delete an email delivery setting
  operationId: DeleteEmailDeliverySetting
  description: |
    Delete an email delivery setting
  responses:
    204:
      description: Email delivery setting was deleted
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
    409:
      $ref: '#/components/responses/Conflict'
patch:
  tags:
    - Email Delivery Settings
  summary: Update an email delivery setting
  operationId: PatchEmailDeliverySettings
  description: |
    Update an email delivery setting
  requestBody:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/EmailDeliverySetting'
    description: Email delivery setting resource
    required: true
  responses:
    200:
      description: Email delivery setting was updated successfully
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/Unauthorized'
    403:
      $ref: '#/components/responses/Forbidden'
    409:
      $ref: '#/components/responses/Conflict'
    422:
      $ref: '#/components/responses/InvalidDataError'
