parameters:
  - $ref: '#/components/parameters/token'
patch:
  tags:
    - Email Delivery Settings
  summary: Verify an email delivery setting
  operationId: VerifyEmailDeliverySettings
  description: |
    Verify an email delivery setting
  requestBody:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/EmailDeliverySetting'
    description: Email delivery setting resource
    required: true
  responses:
    200:
      description: Email delivery setting was verified successfully
      headers:
        Rate-Limit-Limit:
          $ref: "#/components/headers/Rate-Limit-Limit"
        Rate-Limit-Remaining:
          $ref: "#/components/headers/Rate-Limit-Remaining"
        Rate-Limit-Reset:
          $ref: "#/components/headers/Rate-Limit-Reset"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailDeliverySetting'
    401:
      $ref: '#/components/responses/AccessForbidden'
    404:
      $ref: '#/components/responses/NotFound'
